[workspace]

members = [
    "lesson01",
    "lesson02",
    "lesson05",
    "lesson07",
    "lesson09",
    "lesson11/shared",
    "lesson11/client",
    "lesson11/server", "lesson13/client13", "lesson13/server13", "lesson13/shared13",
]
resolver = "2"
